spring:
  application:
    name: zero-boot-web-sample
server:
  port: 8206
logging:
  level:
    root: info

zero:
  boot:
    web:
      enabled: true
      controller-advice: true
      web-log:
    date:
      enabled: true
      date-time-format: yyyy/MM/dd HH:mm:ss
      date-format: yyyy/MM/dd
      time-format: HH:mm:ss